[tools]
uv = "0.6.9"

[settings]
# python management is transferred to uv
disable_tools = ["python"]

[vars]
OUTPUT_COMPOSE_FILE = ".devcontainer/compose.yml"

# devcontainer initialize command task
[tasks.dc-init]
run = [
    "mise run dc-init-001_generate_env",
    "mise run dc-init-002_generate_compose",
    "mise run dc-init-003_check_project",
]
description = "Initialize command for devcontainer"

[tasks.dc-init-001_generate_env]
description = "Generate .env file for compose.yml"
run = [
    'echo "COMPOSE_PROJECT_NAME=$(echo "$(basename -s .git $(git config --get remote.origin.url))-$(git branch --show-current)-$(id -un)")" > .devcontainer/.env',
    'echo "USER_ID=$(id -u)" >> .devcontainer/.env',
    'cat .devcontainer/.env',
]

[tasks.dc-init-002_generate_compose]
description = "Generate compose.yml for devcontainer"
run = '.devcontainer/scripts/i002_generate_compose.sh --verbose -o {{vars.OUTPUT_COMPOSE_FILE}} .devcontainer/compose/base/compose.yml .devcontainer/compose/extend'

[tasks.dc-init-003_check_project]
description = "Check docker compose project override"
run = '.devcontainer/scripts/i003_check_project.sh {{vars.OUTPUT_COMPOSE_FILE}}'


# devcontainer post_create command task
[tasks.dc-post_create-001_install_development_uitls]
description = "Install Development utils using mise"
run = 'mise install'

[tasks.dc-post-create-002_install_pre_commit]
description = "Install pre-commit"
run = 'uv tool install pre-commit'

[tasks.dc-post-create-003_install_pre_commit_hook]
description = "Install pre-commit hook"
run = 'pre-commit install'

[tasks.dc-post_create]
run = [
    "mise run dc-post_create-001_install_development_uitls",
    "mise run dc-post-create-002_install_pre_commit",
    "mise run dc-post-create-003_install_pre_commit_hook",
]
description = "Post create command for devcontainer"

# static-analysis
[tasks.check-lint]
[tasks.check-format]
[tasks.check-type]
[tasks.check-typo]

# static-analysis fix
[tasks.fix-lint]
[tasks.fix-format]
[tasks.fix-type]
[tasks.fix-typo]

# test
[tasks.test-unit]
