[tools]
lefthook = 'latest'
uv = "0.6.9"

[env]
# consolidate uv-related cache in workspace for hardlink in container
UV_CACHE_DIR = "{{config_root}}/.cache/uv/cache"
UV_PYTHON_INSTALL_DIR = "{{config_root}}/.cache/uv/python"
UV_TOOL_DIR = "{{config_root}}/.cache/uv/tool"
UV_TOOL_BIN_DIR = "{{config_root}}/.cache/uv/tool_bin"
_.path = ["{{config_root}}/.cache/uv/tool_bin"]

[settings]
# python management is transferred to uv
disable_tools = ["python"]

[vars]
OUTPUT_COMPOSE_FILE = ".devcontainer/compose.yml"

# devcontainer initialize command task
[tasks.dc-init]
run = ["mise run dc-init-001_generate_compose"]
description = "Initialize command for devcontainer"

[tasks.dc-init-001_generate_compose]
description = "Generate compose.yml for devcontainer"
run = '.devcontainer/scripts/i_generate_compose.sh --verbose -o {{vars.OUTPUT_COMPOSE_FILE}} .devcontainer/compose/base/compose.yml .devcontainer/compose/extend'

# devcontainer post_create command task
[tasks.dc-post_create-001_install_pre_commit_hook]
description = "Install pre-commit hook"
run = 'lefthook install'

[tasks.dc-post_create]
run = ["mise run dc-post_create-001_install_pre_commit_hook"]
description = "Post create command for devcontainer"

# static-analysis
[tasks.check-lint]
[tasks.check-format]
[tasks.check-type]
[tasks.check-typo]
run = "typos"

# static-analysis fix
[tasks.fix-lint]
[tasks.fix-format]
[tasks.fix-type]
[tasks.fix-typo]
run = "typos -w"

# test
[tasks.test-unit]
