
[tasks.dc-post_create]
run = [
    "mise run dc-post_create-001_install_development_utils",
    "mise run dc-post-create-002_install_pre_commit",
    "mise run dc-post-create-003_install_pre_commit_hook",
    "mise run dc-post_create-1000_chown_volume_mount",
    "mise run dc-post_create-1001_setup_chezmoi",
]
description = "Post create command for devcontainer"

[tasks.dc-post_create-1000_chown_volume_mount]
run = ["sudo chown $(id -u):$(id -g) -R ~/.local ~/.config"]
description = "Chown volume mount dir"

[tasks.dc-post_create-1001_setup_chezmoi]
run = '.devcontainer/scripts/_pc_setup_chezmoi.sh ${GITHUB_USERNAME}'
description = "Create dotfiles mount point"
