
[tasks.devcon-post_create]
run = [
    "mise run devcon-post_create-001_install_development_uitls",
    "mise run devcon-post-create-002_install_pre_commit",
    "mise run devcon-post-create-003_install_pre_commit_hook",
    "mise run devcon-post_create-1000_create_mount_point",
]
description = "Post create command for devcontainer"

[tasks.devcon-post_create-1000_create_mount_point]
run = '.devcontainer/scripts/pc1000_setup_chezmoi.sh ${GITHUB_USERNAME}'
description = "Create dotfiles mount point"
