
[tasks.dc-post_create]
run = [
    "mise run dc-post_create-001_install_development_utils",
    "mise run dc-post-create-002_install_pre_commit",
    "mise run dc-post-create-003_install_pre_commit_hook",
    "mise run dc-post_create-1000_install_zsh",
    "mise run dc-post_create-1001_chown_volume_mount",
    "mise run dc-post_create-1002_setup_chezmoi",
]
description = "Post create command for devcontainer"

[tasks.dc-post_create-1000_install_zsh]
run = """
if ! command -v zsh > /dev/null 2>&1; then
    sudo apt update
    sudo apt install -y zsh
    sudo chsh $USER -s /bin/zsh
fi
"""
description = "Install zsh"

[tasks.dc-post_create-1001_chown_volume_mount]
run = ["sudo chown $(id -u):$(id -g) -R ~/.zi"]
description = "Chown volume mount dir"

[tasks.dc-post_create-1002_setup_chezmoi]
run = '.devcontainer/scripts/_pc_setup_chezmoi.sh ${GITHUB_USERNAME}'
description = "Create dotfiles mount point"
