#!/usr/bin/env sh
# Dummy pyenv script for starship
if [ "$1" = "version-name" ]; then
  if [ -n "$PYENV_VERSION" ]; then
    echo "$PYENV_VERSION"
  else
    uv run python --version | sed -e 's/Python //g' -e 's/^/v/'
  fi
else
  echo "Unsupported command: $*" >&2
  exit 1
fi
