version: "3"
includes:
  dist:
    taskfile: taskfile.dist.yml
    flatten: true
    excludes: ["post_create"]

# use for chezmoi(GITHUB_UERNAME) & mise(GITHUB_TOKEN)
dotenv: [".env"]

tasks:
  # Post create
  post_create:
    cmds:
      - task: post_create:001_install_pre_commit
      - task: post_create:1000_setup_chezmoi
    desc: On create command for devcontainer

  post_create:1000_setup_chezmoi:
    # setup dotfiles & dev utils
    cmd: scripts/pc1000_setup_chezmoi.sh ${GITHUB_USERNAME}
    desc: Setup dotfiles & dev utils
