version: "3"
includes:
  dist:
    taskfile: taskfile.dist.yml
    flatten: true
    excludes: ["post_create"]

dotenv: [".env"]

tasks:
  # Post create
  post_create:
    cmds:
      - task: post_create:1000_setup_chezmoi
    desc: On create command for devcontainer

  post_create:1000_setup_chezmoi:
    # setup dotfiles & dev utils
    cmd: post_create/1000_setup_chezmoi.sh ${GITHUB_USERNAME}'
