version: "3"
includes:
  dist:
    taskfile: taskfile.dist.yml
    flatten: true
    excludes: ["post_create"]

tasks:
  # Post create
  post_create:
    cmds:
      - task: post_create:1000_setup_chezmoi
    desc: On create command for devcontainer

  post_create:1000_setup_chezmoi:
    cmd: post_create/1000_setup_chezmoi.sh
    env:
      GITHUB_USERNAME: Di-Is
    desc: Setup dot files & development utilities
