version: "3"
includes:
  dist:
    taskfile: taskfile.dist.yml

tasks:
  default:
    cmds:
      - task --list-all

  # Post create
  post_create:1000_setup_chezmoi:
    cmds:
      - post_create/1000_setup_chezmoi.sh
    env:
      GITHUB_USERNAME: Di-Is
    desc: Setup dot files & development utilities
