services:
  workspace:
    volumes:
      - type: volume
        source: dot_local
        target: /home/ubuntu/.local
      - type: volume
        source:  dot_config
        target: /home/ubuntu/.config
      - type: volume
        source: apt_list
        target: /var/lib/apt/lists
      - type: volume
        source: apt_cache
        target: /var/cache/apt/archives
    env_file:
      - path: devcontainer.env
        required: false

volumes:
  dot_local:
  dot_config:
  apt_list:
  apt_cache:
