services:
  workspace:
    volumes:
      - type: volume
        source: apt_list
        target: /var/lib/apt/lists
      - type: volume
        source: apt_cache
        target: /var/cache/apt/archives
    environment:
      - GITHUB_USERNAME=Di-Is
      - CHEZMOI_DOCKER=false

volumes:
  apt_list:
  apt_cache:
