services:
  workspace:
    volumes:
      - type: volume
        source: apt_list
        target: /var/lib/apt/lists
      - type: volume
        source: apt_cache
        target: /var/cache/apt/archives
    env_file:
      - path: .devcontainer.env
        required: false

volumes:
  apt_list:
  apt_cache:
