name: $COMPOSE_PROJECT_NAME
services:
  workspace:
    build:
      args:
        - USER_ID=$USER_ID
    volumes:
      - type: bind
        source: ..
        target: /home/ubuntu/workspace
      - type: volume
        source: dot_local
        target: /home/ubuntu/.local
      - type: volume
        source:  dot_config
        target: /home/ubuntu/.config
      - type: volume
        source: vscode-server
        target: /home/ubuntu/.vscode-server
    tty: true

volumes:
  vscode-server:
  dot_local:
  dot_config:
