name: $COMPOSE_PROJECT_NAME
services:
  workspace:
    build:
      args:
        - DEVEL_USER_ID=$DEVEL_USER_ID
    volumes:
      - type: bind
        source: ..
        target: /home/ubuntu/workspace
      - type: volume
        source: vscode-server
        target: /home/ubuntu/.vscode-server
    tty: true

volumes:
  vscode-server:
